#!/usr/bin/env bash
set -euo pipefail

PROJECT_ROOT="/home/railab/Desktop/Isaac_HRC"
cd "$PROJECT_ROOT"

HRI_SESSION_ID="$(date +%Y%m%d_%H%M%S_%N)_$$"
export HRI_SESSION_ID

export BHAPTICS_NOTEBOOK_IP=10.3.129.185
export BHAPTICS_UDP_PORT=5005
export BHAPTICS_MIN_INTERVAL=0.08
export ISAAC_XR_MODE=vr
export ISAAC_XR_BACKEND=OpenXR
export WAIT_FOR_VR_TRACKING=1
export DEBUG_HAPTICS_UDP=1
export DEBUG_HAPTICS_COLLISION=0

export ENABLE_HRI_TRAJECTORY_RECORDING="${ENABLE_HRI_TRAJECTORY_RECORDING:-1}"
export HRI_TRAJECTORY_PATH="$PROJECT_ROOT/v3_chan/trajectories/hri_vr_sphere_obs_${HRI_SESSION_ID}.hdf5"
export HRI_TRAJECTORY_OVERWRITE=0
export HRI_TRAJECTORY_MAX_EPISODES=3
export HRI_NEAR_HUMAN_SURFACE_GAP_M="${HRI_NEAR_HUMAN_SURFACE_GAP_M:-0.05}"
export HRI_NEAR_MISS_SURFACE_GAP_M="${HRI_NEAR_MISS_SURFACE_GAP_M:-0.02}"
export HRI_COLLISION_SURFACE_GAP_M="${HRI_COLLISION_SURFACE_GAP_M:-0.0}"
export HRI_HAND_PROXY_RADIUS_M="${HRI_HAND_PROXY_RADIUS_M:-0.035}"
export HRI_DISTANCE_GATE_FULL_GAP_M="${HRI_DISTANCE_GATE_FULL_GAP_M:-0.05}"
export HRI_DISTANCE_GATE_START_GAP_M="${HRI_DISTANCE_GATE_START_GAP_M:-0.13}"
export HRI_GEOMETRY_MAX_QUERY_GAP_M="${HRI_GEOMETRY_MAX_QUERY_GAP_M:-2.0}"
export HRI_GEOMETRY_QUERY_TOLERANCE_M="${HRI_GEOMETRY_QUERY_TOLERANCE_M:-0.00025}"
export HRI_GEOMETRY_QUERY_ITERATIONS="${HRI_GEOMETRY_QUERY_ITERATIONS:-14}"
export HRI_SHOW_PHYSX_COLLIDERS="${HRI_SHOW_PHYSX_COLLIDERS:-0}"
export HRI_DEBUG_SAFETY_VISUALIZATION="${HRI_DEBUG_SAFETY_VISUALIZATION:-0}"
export DEBUG_HRI_SAFETY_GEOMETRY="${DEBUG_HRI_SAFETY_GEOMETRY:-0}"
export HRI_SAFETY_DEBUG_PRINT_EVERY="${HRI_SAFETY_DEBUG_PRINT_EVERY:-30}"

export PICK_PLACE_SUCCESS_XY_TOLERANCE_M=0.04
export PICK_PLACE_SUCCESS_Z_TOLERANCE_M=0.03
export PICK_PLACE_SUCCESS_MAX_SPEED_MPS=0.05
export PICK_PLACE_SUCCESS_MIN_LIFT_M=0.05
export PICK_PLACE_MISS_RECENT_STEPS=30
export PICK_PLACE_CUBE_X_MIN=0.30
export PICK_PLACE_CUBE_X_MAX=0.65

export ENABLE_HRI_VIDEO_RECORDING=0
export ENABLE_GRIPPER_CAMERA=0
export ENABLE_GRIPPER_CAMERA_VIEWPORT=0
export ENABLE_GRIPPER_CAMERA_RECORDING=0

export HAND_TRACKING_UDP_HOST=0.0.0.0
export HAND_TRACKING_UDP_PORT=5555
export XR_EXTERNAL_HAND_TRACKING=0
export XR_HAND_PROXY_ENABLED=0
export XR_HAND_SPHERE_ENABLED=1
export XR_HAND_HAPTIC_POINT_MODE=sphere
export XR_SHOW_CONTROLLERS=1
export XR_CONTROLLER_POSE_MODE=visual
export XR_CONTROLLER_WORKSPACE_GUARD=1
export XR_CONTROLLER_MAX_HEAD_DIST_M=1.85
export XR_CONTROLLER_MIN_Z_M=0.35
export XR_CONTROLLER_MAX_Z_M=2.25
export XR_VIRTUAL_WORLD_POSE_FALLBACK=1
export XR_STAGE_VISUAL_FALLBACK=1
export XR_STAGE_VISUAL_SEARCH_INTERVAL_STEPS=30

export HAPTICS_CONTACT_MIN_STEPS="${HAPTICS_CONTACT_MIN_STEPS:-1}"

LOG_PATH="$PROJECT_ROOT/v3_chan/logs/pick_place_${HRI_SESSION_ID}.log"
mkdir -p "$PROJECT_ROOT/v3_chan/logs" "$PROJECT_ROOT/v3_chan/trajectories"

printf '[Collect] session=%s\n' "$HRI_SESSION_ID"
printf '[Collect] hdf5=%s\n' "$HRI_TRAJECTORY_PATH"
printf '[Collect] log=%s\n' "$LOG_PATH"

./launch_isaac.sh "$PROJECT_ROOT/v3_chan/main.py" 2>&1 | tee "$LOG_PATH"
